# Generated by Django 5.1.6 on 2025-02-22 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_producto_imagen_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagen_producto',
            new_name='imagen',
        ),
    ]
