# Generated by Django 5.1.6 on 2025-02-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_producto',
            field=models.ImageField(blank=True, default='', null=True, upload_to='producto/'),
        ),
    ]
